### ISSUE TITLE
Documentation doesn't tell me where WError comes from

### ISSUE THREAD

**Issue by ronkorving** [davepacheco/node-verror#20]
Hi,

I'll dig into the code and find out for myself. But what I see is that to get a handle on VError, I need to require this module. So how do I access WError? Where does it come from? Do these become globals on require?

Anyway, I'll find out in a minute, but figured I would first write an issue about the lack of clarity on this so it can be addressed.

**Comment by davepacheco** [comment]
As you probably figured out by now, it's a property of the module when you require it.  There's an example here:
https://github.com/davepacheco/node-verror/blob/master/examples/werror.js

**Comment by ronkorving** [comment]
Thanks :)
