### ISSUE TITLE
Documentation doesn't tell me which stack prevails when wrapping errors

### ISSUE THREAD

**Issue by ronkorving** [davepacheco/node-verror#21]
When I pass a cause, which stack prevails? The new VError one's, or the cause's?
Again, I can find out, but the docs probably deserve an update.

**Comment by davepacheco** [comment]
VError does not change the existing semantics of Error (of which it is a subclass).  An Error's stack is fixed when it's constructed.  I believe all of the effects of providing a "cause" argument are documented (modified message, and cause available via cause()).  I'd be happy to take a PR to clarify this point in the docs.
